export interface InformationDeficiency {
  deficiencyAcquired: boolean;
  deficiency: string;
  formTypeDeficiency: string;
  accessSchool: boolean;
  schoolName: string;
  schoolType: string;
  regularEducationClass: boolean;
  specializedEducationalService: string;
  yearCicle: string;
  frequencyDaysWeek: string;
  travelTime: string;
  needsCompany: boolean;
  lackOfAccessibilityWay: boolean;
  barriersWay: string;
  affordableTransportations: boolean;
  typeTransportation: string;
  hasSupportProfessional: boolean;
  needsSupportExtraActivities: boolean;
  physicalBarriersSchool: boolean;
  playWithColleagues: boolean;
  hasCaregiver: boolean;
  primaryCaregiver: string;
  benefitsRecived: string;
  freePublicTransport: boolean;
  accessiblePublicTransport: boolean;
  areaResidence: string;
  housingConditions: string;
}
